config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  post '/checkout', to: "checkouts#gateway"
  get '/checkout/paid', to: "checkouts#paid"
  get '/checkout/failed', to: "checkouts#failed"
  root to: "pages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user, optional: true

  def paid?
    paid_at.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer
  
  has_many :jobs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  def gateway
    job = Job.find(params[:job_id])
    
    if job.paid?
      redirect_to jobs_path, alert: "Already purchased! Job cannot be sold"
      return
    end
    
    price_id = price_ids[job.company.capitalize]
    unless price_id.nil?
      # checkout logic
      redirect_to checkout_paid_path(job_id: params[:job_id])
    else
      redirect_to jobs_path, alert: "Invalid Job"
    end
  end
  
  def paid
    job = Job.find(params[:job_id])
    job.update(paid_at: Time.zone.now, user: current_user)
    redirect_to jobs_path, success: "Congratulations Job purchased"
  end
  
  def failed
    redirect_to jobs_path, alert: "OOPS! Payment failed"
  end

  private

  def price_ids
    YAML.load_file(File.join(__dir__, "..", "..", "price_config.yml"))
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :skip_non_admin_user, except: %i[index]
  before_action :authenticate_user!
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:company, :position, :salary, :paid_at)
    end

    def skip_non_admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(key)
    case key
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Position</th>
      <th>Salary</th>
      <% if current_user.admin? %>
        <th colspan="3">Admin Stuff</th>
      <% else %>
        <th>Sold to</th>
        <th colspan="3">Paid or not?</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.company %></td>
        <td><%= job.position %></td>
        <td><%= number_to_currency(job.salary, precision: 0) %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Show', job %></td>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <% if job.paid_at %>
            <td><%= job.user.email %></td>
            <td><%= button_to 'Paid', root_path, class: "btn btn-success disabled" %></td>
          <% else %>
            <td><%= "Available" %></td>
            <td><%= button_to 'Pay', checkout_path(job_id: job), class: "btn btn-primary" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? %>
  <%= link_to 'New Job', new_job_path %>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>

<p>
  <strong>Paid at:</strong>
  <%= @job.paid_at %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-5">
    <a class="navbar-brand" href="#!">Future Jobs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
          <li class="nav-item">
            <%= link_to  "Jobs", jobs_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to  "Login", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeIntegrationRoroSep2021</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <main class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<header class="bg-dark py-5">
  <div class="container px-5">
    <div class="row gx-5 justify-content-center">
      <div class="col-lg-6">
        <div class="text-center my-5">
          <h1 class="display-5 fw-bolder text-white mb-2">
            Dream job for sale
          </h1>
          <p class="lead text-white-50 mb-4">
            Your children can work for Google, Nasa, Tiktok or Uber
          </p>
          <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
            <%= button_to  "Get Started", new_user_registration_path, method: :get, class:"btn btn-primary btn-lg px-4 me-sm-3" %>
            <a class="btn btn-outline-light btn-lg px-4" href="#!">Learn More</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>